version: "3.9"

services:
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./hellodjango_project/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    container_name: pgdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  dbdata: